function sPPG = create_PPGfast(HW, hfpuls, hfacq, IOs, grad, tRep, CLTime, MixMode, ResetDDS, settingsPPG)
%% Create and prepare MRISequency object
%
%     sPPG = create_PPGfast(HW, hfpuls, hfacq, IOs, grad, tRep, CLTime, MixMode, ResetDDS, settingsPPG)
%
% This is an internal function used by set_sequence. The user should not call it
% directly.
%
% INPUT:
%
%   HW
%         HW structure or object as generated by "LoadSystem"
%
%   hfpuls
%         structure with .NET rf pulse objects (HFPulses)
%
%   hfacq
%         structure with .NET acquisition objects (HFAcquisition)
%
%   IOs
%         structure with .NET arrays with information for digital outputs
%
%   grad
%         structure array with .NET gradient objects (Gradient)
%
%   tRep
%         row vector with repetition times (for .NET) in seconds
%
%   CLTime
%         row vector with command load times in seconds
%
%   MixMode
%         array with indices for the mixer mode
%
%   ResetDDS
%         logical row vector to mark tReps for which the DDS clock should be
%         reset (phase reference)
%
%   settingsPPG
%         structure with additional settings for the PPG:
%     init
%           logical to indicate if the initialization commands should be
%           prepended to the pulse program
%     iDevice
%           index of the MMRT device the PPG applies to
%     syncDevices
%           logical to indicate that secondary devices should start synchronized
%           with the primary device.
%     tRepIsTriggered
%           logical row vector to mark tReps which wait for an external trigger
%           to start
%     tRepTriggerDebounceTime
%           row vector with debounce time of trigger in seconds
%     auxCommands
%           FPGA commands (64-bit unsigned integers) that are prepended to the
%           commands for each respective tRep
%
%
% OUTPUT:
%
%   sPPG
%         .NET object with the compiled sequence (inside a Matlab wrapper)
%
% ------------------------------------------------------------------------------
% (C) Copyright 2011-2025 Pure Devices GmbH, Wuerzburg, Germany
% www.pure-devices.com
% ------------------------------------------------------------------------------

end


%#function PD.MRISequence
%#function PD.PPGWrapper
%#function PD.SequenceCommands
%#function hex2uint64

