function [Vn] = aptRotate(n, alfa, phi, theta)

    Rx=[...
        1                   ,0                  ,0;...
        0                   ,cos(alfa)  ,-sin(alfa);...
        0                   ,sin(alfa)  ,cos(alfa)];

    Ry=[...
        cos(phi)    ,0                  ,sin(phi);...
        0                   ,1                  ,0;...
        -sin(phi)   ,0                  ,cos(phi)];

    Rz=[...
        cos(theta)  ,-sin(theta),0;...
        sin(theta)  ,cos(theta) ,0;...
        0                   ,0                  ,1];
    
    Vn=zeros(size(n));
    for t=1:size(n,1)
        Vn(t,:)=Rz*(Ry*(Rx*n(t,:).'));
    end
    
end