function [methodinfo,structs,enuminfo,ThunkLibName]=isMouseButtonPressed_user32_proto64
%ISMOUSEBUTTONPRESSED_USER32_PROTO64 Create structures to define interfaces found in 'user32'.

%This function was generated by loadlibrary.m parser version  on Fri Jul  6 16:18:58 2018
%perl options:'user32.i -outfile=isMouseButtonPressed_user32_proto64.m -thunkfile=user32_thunk_pcwin64.c -header=user32.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'isMouseButtonPressed_user32_thunk_pcwin64');
% short GetAsyncKeyState ( int vKey ); 
fcns.thunkname{fcnNum}='int16int32Thunk';fcns.name{fcnNum}='GetAsyncKeyState'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int16'; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
methodinfo=fcns;